# Site settings
title: Echcz's Blog
SEOTitle: Echcz Blog
header-img: img/home-bg.jpg
email: echcz@outlook.com
description: "这里是Echcz的个人博客。关于程序与设计，探索与创造。期待与你一起发现更大的世界。"
keyword: "echcz | blog | 博客 | 互联网 | Web | 程序 | 设计"
url: "https://echcz.github.io"              # your host, for absolute URL
baseurl: "/blog"                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     echcz
zhihu_username:     echcz
github_username:    echcz
#twitter_username:   your_name
#facebook_username:  yourt_name
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md",".idea","blog.iml"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN
# excerpt separator for generated excerpt
excerpt_separator: "\n\n\n"



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: your_name

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-xxxxxx-xx'            # Format: UA-xxxxxx-xx
#ga_domain: echcz.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "路漫漫其修远兮<br>&nbsp;&nbsp;吾将上下而求索"
sidebar-avatar: /blog/img/avatar-echcz.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
{
  title: "Jessie的秘密blog",
  href: "http://windykitty.gitee.io/jessiekittyblog/"
},{
  title: "纯洁的微笑",
  href: "http://www.ityouknow.com/"
},{
  title: "程序员DD",
  href: "http://blog.didispace.com/"
},{
  title: "Bigdata Blog",
  href: "http://bigdata-blog.net/"
},{
  title: "廖雪峰的官方网站",
  href: "https://www.liaoxuefeng.com/"
},{
  title: "阮一锋的网络日志",
  href: "http://www.ruanyifeng.com/blog/"
}
]
